import type { Metadata } from 'next';

import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';

import '@/styles/globals.css';

import FloatingButton from '@/components/FloatingButton';
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';

dayjs.extend(utc);

import {
  gothicA1,
  nanumGothic,
  notosans,
  poppins,
  roboto,
} from '@/styles/fonts';

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen ${notosans.className} ${poppins.variable} ${roboto.variable} ${nanumGothic.variable} ${gothicA1.variable} antialiased`}>
        <Header />
        <main className="px-6 pt-20 overflow-x-hidden pb-14 md:px-10 lg:pt-28 lg:py-20 ">
          {children}
        </main>
        <FloatingButton />
        <Sidebar />
      </body>
    </html>
  );
}
