import type { Metadata } from 'next';

import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';

import '@/styles/globals.css';

import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';

dayjs.extend(utc);

import {
  gothicA1,
  nanumGothic,
  notosans,
  poppins,
  roboto,
} from '@/styles/fonts';

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notosans.className} ${poppins.variable} ${roboto.variable} ${nanumGothic.variable} ${gothicA1.variable} antialiased`}>
        <div className="w-screen h-screen">
          <Header />
          <main className="relative h-[calc(100%_-_56px)] px-5 py-10 pb-14 overflow-x-hidden md:px-10 lg:py-20 ">
            {children}
          </main>
          <Footer />
          <Sidebar />
        </div>
      </body>
    </html>
  );
}
